import Head from 'next/head'

import TopNav from '../components/TopNav'
import ContentFeed from '../components/ContentFeed'
import BottomNav from '../components/BottomNav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Plastagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
      <ContentFeed />
      <BottomNav />
    </div>
  )
}
