import Head from 'next/head'

import TopNav from '../components/TopNav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Plastagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav/>
    </div>
  )
}
